### ISSUE TITLE
FTBFS: cbindgen

### ISSUE THREAD

**Issue by imjasonh** [wolfi-dev/os#23862] opened 2024-07-12 14:38 UTC
```
ERROR: Couldn't execute `cargo metadata` with manifest "/home/build/Cargo.toml": Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

There's also this line, which indicates we're building using a floating latest nightly rustc, when we should probably be building with a non-moving rustc, that we boostrap and build ourselves.

```
nightly-x86_64-unknown-linux-gnu installed - rustc 1.81.0-nightly (0c81f94b9 2024-07-10)
```

https://cloudlogging.app.goo.gl/Mxqx98ropc2sK78T7

**Comment by justinvreeland** [comment] 2024-08-12 22:27
Seems like the build issue is transient failure, or at least I cannot reproduce it. I'm able to build cbingen just fine.  As for the nightly that seems to be part of the test stage and looks intentional.

**Comment by justinvreeland** [comment] 2024-10-01 15:54
Closing this because cbingen builds fine these days.

**Closed by justinvreeland** 2024-10-01 15:54 UTC
Labels: squad:foundations, service:ftbfs
